import cart from './cart.png'
import github from './github.png'
import google from './google.png'
import logo from './logo.png'
import banner from './banner.jpg'
import banner2 from './banner2.jpg'
import banner3 from './banner3.jpg'
import pdp from './pdp.jpg'
import payment from './payment.png'
export { github, logo, cart, google, payment, banner, banner2, banner3, pdp }
